name: Fun-with-Flags - CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_PROD_URL: ${{ secrets.VERCEL_PRODUCTION_DOMAIN }}

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        run: action/checkout@v3

      - name: Install dependecies
        run: npm intall

      - name: Build project
        run: npm run build

      - name: Vercel Deploy
        run: amondnet/vercel-action@v25
